"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.prisma = void 0;
var dotenv_1 = require("dotenv");
var client_js_1 = require("./generated/client.js");
var adapter_pg_1 = require("@prisma/adapter-pg");
var path_1 = require("path");
dotenv_1.default.config({ path: path_1.default.resolve(process.cwd(), "../../.env"), });
var adapter = new adapter_pg_1.PrismaPg({ connectionString: process.env.DATABASE_URL });
exports.prisma = new client_js_1.PrismaClient({ adapter: adapter });
